### ISSUE TITLE
页脚进行升级

### ISSUE THREAD

**Issue by hasmokan** [hasmokan/software-frontend#2]
## 页脚升级
> **现有的页脚过于简陋，需要重构**

![image](https://github.com/hasmokan/software-frontend/assets/112612128/167512e2-cf1a-4e62-9280-31ea7bf5b93a)

> **示例图**

![image](https://github.com/hasmokan/software-frontend/assets/112612128/858edb8c-e564-4e44-aab5-75e1598f53a7)

**Comment by WangjiaweiY** [comment]
got it
